title: Batuhan Edgüer
subtitle: Data Scientist | Biomedical Engineer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Resume
      url: /resume
    - text: Blog
      url: /blog
#    - text: Gallery
#      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact


# Edit these details

author_logo: profile.png
author: Batuhan Edgüer
author_bio: Hi, my name is Batuhan Edgüer.
author_email: "batuhanedguer@gmail.com"
author_location: Turkey
author_website_url: https://bestsithineu.github.io
typewrite-text: Hello, I’m Batuhan Edgüer, welcome to my blog. Since July 2020.

author_work_experiences:
            - company_name: Yeditepe University / Andaç Hamamcı - Istanbul
              company_logo: yeditepe.jpg
              company_url: https://yeditepe.edu.tr
              designation: Medical Imaging Laboratory Assistant
              description: Helped students learn & generate medical imaging software based on Python and 3DSlicer. Between March 2018 to June 2020.
              visibility: true
            - company_name: Adana Seyhan Devlet Hastanesi
              company_logo: hastane.png
              company_url: https://seyhandh.saglik.gov.tr/
              designation: Biomedical Engineer Intern
              description: Inspected all laboratory and manufacturing equipment and immediately sent any non-working devices out for repair. Between July 2018 to August 2018.
              visibility: true

author_education_details:
              - college_logo: yeditepe.jpg
                college_name: Yeditepe University
                college_url: https://yeditepe.edu.tr
                college_degree: Biomedical Engineer
                description: Bachelor Degree. Between September 2013 to June 2020.
                visibility: true

author_project_details:
              - project_thumbnail: slicer.png
                project_title: Tumor - Cut
                project_description: A module built for 3D Slicer for tumor segmentation. (Lang. Python)
                project_url: https://youtu.be/neLys0pjhPs
                visibility: true

# social links
github_username:  BestSithInEU
facebook_username: batuhan.edguer
linkedin_username: batuhan-edgüer-07714b91
#behance_username: johndoe
instagram_username: batuhanedguer
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1123

# wakatime username (coding activity)
wakatime_username: BestSithInEU

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: batuhanedguer@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: 0XJDZ6JVUB
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: c204ff6fa69a8a704df6946a489e75d3

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
